BROKER_URL = 'memory://'
STAGECRAFT_URL = 'http://stagecraft'
STAGECRAFT_OAUTH_TOKEN = 'development-oauth-access-token'
BACKDROP_READ_URL = 'http://backdrop/data'
BACKDROP_WRITE_URL = 'http://backdrop/data'
