#!/usr/bin/env bash

function is_govuk_infrastructure {
  [ -n "$GOVUK_APP_NAME" ]  
}

if is_govuk_infrastructure; then
	BACKDROP_APP=$(echo $GOVUK_APP_NAME | cut -d . -f 1)
	cp Procfile-$BACKDROP_APP Procfile
fi
