DATABASE_NAME = "backdrop_test"
MONGO_HOSTS = ['localhost']
MONGO_PORT = 27017
LOG_LEVEL = "ERROR"

DATA_SET_RATE_LIMIT='10000/second'

from development import STAGECRAFT_URL, STAGECRAFT_DATA_SET_QUERY_TOKEN, SIGNON_API_USER_TOKEN
